### ISSUE TITLE
Unable to save profile

### ISSUE THREAD

**Issue by vleput** [Inrupt-inc/generator-solid-angular#8]
I'm unable to update my profile via the app: 

**Steps to reproduce :**
- Generate the angular project
- Serve it
- Login
- Get to the Profile page & edit profile properties
- Click "Save"
- Console logs: `Error: Error: Missing IRI for NamedNode  card.component.ts:68:8`

Updating my profile via the solid.community/profile/card#me page works fine, and data is then properly read in the angular app.

Reproduced on: Chromium 69 + Firefox 62

**Comment by james-martin-jd** [comment]
I have a fix for this coming shortly, but it doesn't account for email/phone fields. These are different in the profile because you only have one first name, role, etc. but you can have multiple named phone numbers (work, home, cell, etc). I opened a new bug for email/phone. 

A workaround for now is if you add a phone or email in the pod itself, you can then use this app to change it. I'll be investigating the phone/email fields shortly.
